### ISSUE TITLE
Client: Enable passing labels via env var or parameter

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2188]
## Situation
The newly introduced feature of passing labels (https://mercedes-benz.github.io/sechub/latest/sechub-client.html#labels) enables to set labels and get them passed to the reports.

Currently, one has to define labels inside the `sechub.json`.
Due to `sechub.json` is rather static, it would be great to pass labels to the SecHub client via
- a parameter - E.g. `sechub -label <key1>=<value1> -label <key2>=<value2>`
- or an environment variable - E.g. `export SECHUB_LABELS="<key1>=<value1>,<key2>=<value2>"`

## ToDo
- [x] Implement above idea.

- [x] It shall be possible to define labels in `sechub.json`, via parameter and via environment variable at the same time.
So the union of all will be passed to the SecHub server.

- [x] On identical keys, the usual override mechanism comes into force:
parameters (commandline options) override
__environment variables override
____config JSON file

- [x] provide documentation
