### ISSUE TITLE
pds-xray: release and build

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#2762]
## Situation
PDS-Xray programming is done. Now release and build jobs need to be completed.

## ToDo
- [x] create Xray Wrapper release job
  - test it
- [x] change `Xray-Debian.dockerfile` from local jar to download from release
  - env variable: add XRAY_WRAPPER_VERSION
  - also add an option for providing a local jar to be copied into the image
- [ ] Image build of pds-xray
  - add XRAY_WRAPPER_VERSION to `_build+publish-pds-solution.yml`
  - add pds-xray to `build+publish-all-pds-solutions.yml`
  - test both
