### ISSUE TITLE
EPIC: provide server problem messages for users

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#297]
### PDS
When a PDS has been started and a special problem ocurres which can be only handled from caller side (e.g. when a PDS needs a file inside sources e.g. a special build file, but its' is not uploaded) the problem shall be visible to user.

### Common
At the moment we generate a "pseudo" critical warning and show inside report that a product is not available and so we have no correct output here.

But this a little bit odd, because we mix up security findings with technical problems.

To avoid this we must differ this as well. 

### Client
- [x] sechub client shall show user messages #301

### PDS
- [x] PDS techfailures and user messages are written to disk in appropriate format. PDS stores this problem message inside JOB in a special column of DB, will be done with #299 
- [x] Caller (SecHub) can fetch those information and will add this to sechub job problem descriptions so it's available for client, will be done with #300

### SecHub server
- [x] sechub format change: add technical problems sections inside json
     will be done with #298

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>
