### ISSUE TITLE
Handle SecHub configuration encryption at SecHub server

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#3263]
## Situation
Currently the user configuration is not encrypted.

With #837 we have now some security helper classes which provide a secure way to handle this.

:information_source: _This is a sub issue of #3250_ 

## Wanted 
We want user configuration data encrypted inside database. So user credentials inside configurations will be stored encrypted inside database

## Solution

- [x]  Introduce new table to hold encryption data for cluster (use concept created in epic #3250 )
- [x] Write migration sql flyway script - NONE encryption after migration
- [x] Startup phase blocks when a server does not support encryption / sanity check fails
- [x] Schedule job will only fetch jobs which have supported encryption
      (means trigger service repository call needs changes)
- [x] Introduce UC for Automatically update existing jobs which are done via a trigger service (spring scheduling)
- [x] Introduce REST endpoint + UC for admins to trigger cipher rotation (means add new cipher pool entry which is used as latest one + check encryption works)
- [x] Introduce REST endpoint + UC for admins to check cipher pool situation (which are used)
- [x] Autocleanup process does also 
      internal check is still done that there are no longer jobs which uses this pool id entry, also the latest will never be deleted...
- [x] New jobs have automatically encrypted configuration of latest supported entry from cipher pool.
- [x] Introduce UC for cipher pool refresh inside `ScheduleEncryptionService`
   (for all server instances in cluster)
- [ ] Update OpenAPI file definition for new REST endpoints.
