### ISSUE TITLE
Client: Extend false-positives handling for projectData

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#3390]
## Situation
Since SecHub server 2.1.0 the false-positive declaration has been extended by a `projectData` section.
See https://mercedes-benz.github.io/sechub/latest/sechub-architecture.html#section-concept-false-positive-general-api-centric 

## ToDo
- [x] add above to the SecHub client documentation (include sechub-doc/src/docs/asciidoc/documents/shared/false-positives/false-positives-howto-define-by-api.adoc)
- [x] action `markFalsePositives` is able to process `projectData` section
- [x] action `unmarkFalsePositives` is able to process `projectData` section
- [x] action `defineFalsePositives` is able to process `projectData` section
- [x] to check: action `getFalsePositives`
- [x] no change in action `interactiveMarkFalsePositives` - this refers only to single findings
- [x] action `interactiveUnmarkFalsePositives` - is able to process `projectData`
